### ISSUE TITLE
WebP

### ISSUE THREAD

**Issue by sindresorhus** [mathiasbynens/small#24]
Smallest possible WebP image.

Seen it done with [gif](http://probablyprogramming.com/2009/03/15/the-tiniest-gif-ever). Would be cool to see how small WebP could be.

**Comment by alokmenghrajani** [comment]
https://github.com/alokmenghrajani/random_stuff/blob/master/spacer.webp

**Comment by mathiasbynens** [comment]
@alokmenghrajani Nice work! Care to submit a pull request?
