### ISSUE TITLE
Can't play mp4.mp4 with html5

### ISSUE THREAD

**Issue by chevett** [mathiasbynens/small#36]
I've setup a test page: http://filibuster.herokuapp.com/mobile-video/blank.html

I've copied mp4.mp4 to small.mp4.  If you open the test page you will see that big.mp4 loads and can play no problem.  However, there is an error event while loading small.mp4 and you cannot right click to play small.mp4.  I'm pretty sure I am doing it right.  Agree/disagree?

Any ideas?  Thanks!

@kalifg

**Comment by waldyrious** [comment]
That issue was closed as WontFix, with the justification that the contents of the file are MPEG-4 SP and not H.264. Does this affect the validity of the .mp4 file? Maybe we should have more than one version of minimal mp4 files, each with a different codec?

**Comment by mhofman** [comment]
It would be awesome if we could get an MP4 file containing an H.264 stream.
