### ISSUE TITLE
C code is implementation dependent

### ISSUE THREAD

**Issue by Matheus28** [mathiasbynens/small#39]
According to the C99 standard:

>The function called at program startup is named main. The implementation declares no
prototype for this function. It shall be defined with a return type of int and with no
parameters:
>
>     int main(void) { /\* ... \*/ }
>or with two parameters (referred to here as argc and argv, though any names may be
used, as they are local to the function in which they are declared):
>
>     int main(int argc, char \*argv[]) { /\* ... \*/ }
> or equivalent;10) or in some other implementation-defined manner.

Also, it requires a new line at the end:

> A nonempty source file does not end in a new-line character which is not immediately
preceded by a backslash character or ends in a partial preprocessing token or
comment (5.1.1.2).

(Section J.2 Undefined behaviour)

So if you want something that should work in all implementations that conform to the standard, the file `c.c` has to be (`return 0;` is implied at the end, as per 5.1.2.2.3).

    int main(void){}
    

(With a newline at the end, 17 bytes in total)

**Comment by mathiasbynens** [comment]
Thanks!
