### ISSUE TITLE
WAV question

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/small#52]
@angea https://code.google.com/p/corkami/source/browse/trunk/src/PoCs/posters/mini.wav is 52 bytes, but https://github.com/mathiasbynens/small/blob/master/wav.wav is only 44 bytes. Do you see anything wrong with the latter file?

See #50. cc @mgeier

**Comment by angea** [comment]
my mini files are not "as small as possible"
(I call those "tiny", not "mini")

Mini.wav has some significance:
it actually makes some sound, a bit the "hello world" of WAV:
https://github.com/corkami/pics/blob/master/WAV.png

**Comment by mathiasbynens** [comment]
Thanks for clarifying!
