### ISSUE TITLE
html5.html is invalid

### ISSUE THREAD

**Issue by zzzzBov** [mathiasbynens/small#75]
`<!DOCTYPE html>` isn't valid HTML5 courtesy of https://html5.validator.nu/

At a minimum, the `title` element is required, and it must have a value:

```
<!DOCTYPE html><title>_</title>
```

is the smallest valid HTML5 document that I'm aware of.

**Comment by mathiasbynens** [comment]
See <https://mathiasbynens.be/notes/minimal-html#5> as mentioned in the README.
