### ISSUE TITLE
Request: png

### ISSUE THREAD

**Issue by fulldecent** [mathiasbynens/small#78]
I see the smallest transparent png. But is that necessarily the smallest png?

**Comment by landfillbaby** [comment]
the smallest png without an alpha channel is also 67 bytes.
http://garethrees.org/2007/11/14/pngcrush/

**Comment by ace-dent** [comment]
The smallest, compliant PNG is 67 bytes. Suggest Closing issue.

**Comment by fulldecent** [comment]
Great reference, closing, thank you
